name: Hello World Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      ORG_KUBECONFIG: ${{ secrets.ORG_KUBECONFIG }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Hello World Action
      uses: k8s-adventures/test-action/.github/actions/test-action@main
