name: Hello World Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Hello World Action
      uses: k8s-adventures/test-action/.github/actions/test-action@main
      with:
        org_test_secret: ${{ secrets.ORG_TEST_SECRET }}
